---
- import_tasks: cleanup.yaml

- import_tasks: generate_manifests.yaml

- import_tasks: prometheus-operator.yaml
  when:
    - "status.monitoring is not defined or status.monitoring.status is not defined or status.monitoring.status != 'enabled'"

- import_tasks: node-exporter.yaml
  when:
    - "status.monitoring is not defined or status.monitoring.status is not defined or status.monitoring.status != 'enabled'"

- import_tasks: kube-state-metrics.yaml
  when:
    - "status.monitoring is not defined or status.monitoring.status is not defined or status.monitoring.status != 'enabled'"

# - import_tasks: prometheus-adapter.yaml

- import_tasks: grafana.yaml
  when:
    - monitoring.grafana is defined
    - monitoring.grafana.enabled is defined
    - monitoring.grafana.enabled == true

- import_tasks: prometheus.yaml
  when:
    - "status.monitoring is not defined or status.monitoring.status is not defined or status.monitoring.status != 'enabled'"

- import_tasks: devops.yaml

- import_tasks: etcd.yaml

- import_tasks: prometheus-rules.yaml
  when:
    - "status.monitoring is not defined or status.monitoring.status is not defined or status.monitoring.status != 'enabled'"

- import_tasks: alertmanager.yaml
  when:
    - "status.monitoring is not defined or status.monitoring.status is not defined or status.monitoring.status != 'enabled'"

- import_tasks: notification-manager.yaml

- import_tasks: monitoring-dashboard.yaml
  when:
    - "status.monitoring is not defined or status.monitoring.status is not defined or status.monitoring.status != 'enabled'"

- name: Monitoring | Importing ks-monitoring status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"monitoring": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kubesphere-system
  register: import
  failed_when: "import.stderr and 'Warning' not in import.stderr"
  until: import is succeeded
  retries: 5
  delay: 3
  when:
    - "status.monitoring is not defined or status.monitoring.status is not defined or status.monitoring.status != 'enabled'"

- import_tasks: thanosruler.yaml
  when:
    - alerting is defined
    - alerting.enabled is defined
    - alerting.enabled == true
